const logo=document.querySelector('#logo')
const resumo=document.querySelector('#resumo')
const filme_1=document.querySelector('#filme_1')
const filme_2=document.querySelector('#filme_2')
const filme_3=document.querySelector('#filme_3')
const filme_4=document.querySelector('#filme_4')

filme_1.addEventListener('click',filme1)
filme_2.addEventListener('click',filme2)
filme_3.addEventListener('click',filme3)
filme_4.addEventListener('click',filme4)

function filme1(){
    logo.src="img/terrifier.jpg"
    resumo.textContent=`Até o momento, Terrifier 3 ainda não foi lançado, mas há muita expectativa em torno de sua produção. O filme foi confirmado e está em desenvolvimento, seguindo o sucesso de Terrifier (2016) e Terrifier 2 (2022), ambos dirigidos por Damien Leone e centrados no icônico vilão Art the Clown.Terrifier 2 se tornou um grande sucesso de público e crítica, especialmente por sua abordagem ainda mais ousada e sangrenta em relação ao gore e ao terror psicológico, o que fez o personagem Art the Clown ganhar uma base de fãs muito fiel. O filme também gerou bastante discussão pela duração, as sequências de tortura e pelo final aberto, que deixou espaço para uma continuação.Embora detalhes específicos sobre o enredo de Terrifier 3 não tenham sido divulgados oficialmente até a data do meu último treinamento (outubro de 2023), sabe-se que Damien Leone e a produtora Iconic Events ainda estão trabalhando para expandir a história de Art, incluindo novos desafios e situações aterrorizantes. Especula-se que Terrifier 3 possa continuar explorando a jornada do vilão psicótico Art, talvez com novos personagens e, é claro, mais cenas de violência explícita e assombração.Portanto, por enquanto, Terrifier 3 está em produção e promete continuar o legado do mais assustador do cinema contemporâneo. A data de lançamento e detalhes adicionais provavelmente serão anunciados em breve.`
}
function filme2(){
    logo.src="img/Corra-1024x577-1.jpg"
    resumo.textContent=`Corra! (título original Get Out) é um thriller psicológico de 2017, escrito e dirigido por Jordan Peele. O filme mistura elementos de horror com crítica social e aborda questões raciais nos Estados Unidos.A trama segue Chris Washington (interpretado por Daniel Kaluuya), um jovem negro que vai passar um fim de semana na casa dos pais de sua namorada, Rose Armitage (Allison Williams). Quando chega à propriedade dos Armitage, Chris começa a perceber comportamentos estranhos dos empregados e dos próprios anfitriões, que tentam esconder um desconforto latente em relação à sua presença.À medida que o fim de semana avança, Chris descobre que os Armitage têm um segredo macabro envolvendo o uso de pessoas negras para experimentos científicos. O filme mistura uma atmosfera de suspense crescente com uma reflexão crítica sobre o racismo estrutural, o fetichismo racial e a exploração histórica dos negros na sociedade.Corra! foi aclamado pela crítica por sua habilidade em mesclar tensão e crítica social, sendo um marco no gênero de terror contemporâneo. O filme também se destacou por seu enredo original e pelo uso de metáforas que abordam a opressão racial nos dias atuais. O desempenho de Daniel Kaluuya foi amplamente elogiado, e o filme ganhou vários prêmios e indicações, incluindo uma indicação ao Oscar de Melhor Roteiro Original.`
}
function filme3(){
    logo.src="img/1012_c.jpg"
    resumo.textContent=`Nos momentos derradeiros do terror, vemos apenas que a protagonista entendeu que precisava superar seus traumas, mas chegou a essa conclusão tarde demais. Mesmo fugindo para ficar sozinha e ninguém a ver cometendo suicídio, ela passa a maldição para a próxima pessoa, Joel, que por ter ido atrás dela, presencia a cena.A entidade se manifesta como a mãe falecida de Rose, uma figura que simboliza a dor emocional que a personagem carrega desde a infância. Essa metáfora para o trauma e a culpa é explorada quando Rose volta à sua casa de infância, onde sua mãe morreu, na tentativa de enfrentar e superar a maldição.`
}
function filme4(){
    logo.src="img/20277419.jpg"
    resumo.textContent=`(Sinister, 2012) é um filme de terror psicológico dirigido por Scott Derrickson e escrito por C. Robert Cargill. O filme segue Ellison Oswalt (interpretado por Ethan Hawke), um escritor de livros de crime que se muda com sua família para uma casa nova, com o objetivo de investigar o caso de uma família que foi assassinada ali anos antes. Ellison espera que o crime seja o suficiente para inspirar seu próximo livro e restaurar sua carreira, que está em declínio.Ao investigar o caso, Ellison encontra uma caixa de filmes caseiros que mostram a família sendo brutalmente assassinada, mas também capturam imagens perturbadoras de outros assassinatos de diferentes famílias, todas aparentemente relacionadas àquela casa. Conforme Ellison vai assistindo aos vídeos, ele percebe que as mortes têm algo em comum: todas estão ligadas a uma entidade maligna chamada Bagul, um ser sobrenatural que se alimenta das almas das crianças.À medida que Ellison fica obcecado pela investigação, ele começa a perceber que sua própria família está sendo perseguida por forças sobrenaturais. Sua esposa, Tracy (interpretada por Juliet Rylance), e seus filhos começam a ter experiências estranhas e aterrorizantes, e a situação vai piorando à medida que Ellison se afasta de sua família e se aprofunda cada vez mais no mistério.O filme tem uma atmosfera sombria e tensa, explorando o medo do desconhecido e o impacto do sobrenatural sobre a vida de uma pessoa. Além disso, o conceito de Bagul e a conexão entre os assassinatos e o mal antigo criam uma sensação crescente de pavor e fatalidade. O clímax do filme é altamente impactante, levando a um final sombrio e inesperado, que deixa uma sensação de angústia no público.`
}
